-- AlterTable
ALTER TABLE "cat_permisos" ADD COLUMN     "caracter" VARCHAR(100),
ADD COLUMN     "claveidentificaciontanque" VARCHAR(100),
ADD COLUMN     "claveinstalacion" VARCHAR(100),
ADD COLUMN     "descripcioninstalacion" VARCHAR(100),
ADD COLUMN     "estadotanque" VARCHAR(20),
ADD COLUMN     "incertidumbremedicionsistmediciontanque" REAL NOT NULL DEFAULT 0.000,
ADD COLUMN     "localizacionyodescripciontanque" VARCHAR(200),
ADD COLUMN     "localizodescripsistmediciontanque" VARCHAR(200),
ADD COLUMN     "modalidadpermiso" VARCHAR(100),
ADD COLUMN     "numerodispensarios" SMALLINT,
ADD COLUMN     "numeroductosentradasalida" SMALLINT,
ADD COLUMN     "numeroductostransportedistribucion" SMALLINT,
ADD COLUMN     "numeropozos" SMALLINT,
ADD COLUMN     "numerotanques" SMALLINT,
ADD COLUMN     "sistemamediciontanque" VARCHAR(100),
ADD COLUMN     "valornumericocapacidadfondajetanque" REAL NOT NULL DEFAULT 0.000,
ADD COLUMN     "valornumericocapacidadoperativatanque" REAL NOT NULL DEFAULT 0.000,
ADD COLUMN     "valornumericocapacidadtotaltanque" REAL NOT NULL DEFAULT 0.000,
ADD COLUMN     "valornumericocapacidadutiltanque" REAL NOT NULL DEFAULT 0.000,
ADD COLUMN     "valornumericovolumenminimooperacion" REAL NOT NULL DEFAULT 0.000,
ADD COLUMN     "vigenciacalibracionsistmediciontanque" DATE,
ADD COLUMN     "vigenciacalibraciontanque" DATE;
